# Logging
project_name: framework-tests
logger: local
# Model Class (S, L, M)
model: M
positive_freqs: False

# Network
in_features: 1
out_features: 1
hidden_layers: 1
hidden_features: [[2, 16], [4, 32], [4, 32]]
bias: True
max_stages: 3

period: 2
pmode: wrap
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [4, 6, 8]
hidden_omega_0: 30
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0', 'd1']

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1}
optim_handler: 'regular'

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.00000000001
diff_tol: 0.0000001
max_epochs_per_stage: 300
batch_size: 128 * 128

# Data
data_path: data/arrays/sinusoidal.npy

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]
zoom: [2, 4]
zoom_filters: ['linear', 'cubic', 'nearest']