# Model Variant (S, L, M)
model: M

# Network
in_features: 2
hidden_layers: 1
hidden_features: [25, 81, 289]
bias: True
periodic: True
max_stages: 3

# Frequency Initialization
omega_0: [4, 8, 16] 
hidden_omega_0: [30, 30, 30, 30]
superposition_w0: True

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [8001, 4001, 2001, 1000]
batch_size: 1
batch_samples_perc: 1.0

# Image
image_name: periodic.png
width: 256
height: 256
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cpu
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-3, 3] 








