
omega_0: [8, 16, 32, 64] 
in_features: 2

hidden_features: [64, 64, 96, 96]
hidden_layers: 1

superposition_w0: True
hidden_omega_0: [30, 30, 30, 30]

sampling_scheme: poisson
multiresolution: gauss_pyramid

max_epochs_per_stage: [500, 500, 600, 600]
opt_method: Adam

attributes: ['d0', 'd1']
loss_function: 'mse'
visualize_grad: True

lr: 0.0001
loss_tol: 0.000001
diff_tol: 0.0000000000001

batch_samples_perc: 1.
batch_size: 1

image_name: lena.png

width: 128
height: 128

channels: 1
max_stages: 4

model: M

# Remember to only vary between 'cuda' and 'cpu'
device: cuda 
eval_device: cpu

bias: False

#save_format: 'general'
#extrapolate: [-3, 3] 


