# Model Variant (S, L, M)
model: M

# Network
in_features: 3
hidden_layers: 1
hidden_features: [120, 80, 100, 160]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [8, 16, 48]
hidden_omega_0: [30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: False
filter: none # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [10, 500, 500, 500]
batch_size: 1
batch_samples_perc: 1.0

# Image
image_name: wood_noise3d128.npy
width: 128
height: 128
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cpu
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-3, 3]








