
omega_0: 128
in_features: 2

hidden_features: 256
hidden_layers: 3

superposition_w0: True
hidden_omega_0: 30

sampling_scheme: stratified
decimation: pyramid
filter: gauss # vary between none, laplace and gauss

max_epochs_per_stage: 700
opt_method: Adam

attributes: ['d0', 'd1']
loss_function: 'hermite'

lr: 0.0001
loss_tol: 0.000001
diff_tol: 0.0000000000001

batch_samples_perc: 1.
batch_size: 1

image_name: lena.png

width: 128
height: 128

channels: 1
max_stages: 1

model: L

# Remember to only vary between 'cuda' and 'cpu'
device: cuda
eval_device: cpu

bias: False

#save_format: 'general'
#extrapolate: [-3, 3] 


