# Model Variant (S, L, M)
model: M

# Network
in_features: 3
out_features: 3
hidden_layers: 1
hidden_features: [[9, 16], 1024, 512, 1024]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [1, 24, 6, 16]
hidden_omega_0: [30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1, 'd1': 0}

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.000000000001
diff_tol: 0.000000001
max_epochs_per_stage: [10, 50, 5, 5]
batch_size: 128 * 128 * 2

# Image
filename: procedural
width: 256
height: 256
depth: 256
channels: 3

test_mesh: bunny.obj
ntestpoints: 290000

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]








