# Model Variant (S, L, M)
model: M

# Network
in_features: 2
hidden_layers: 3
hidden_features: [256]
bias: True
max_stages: 1

# Frequency Initialization
omega_0: [30] 
hidden_omega_0: [30]
superposition_w0: True

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [4000]
batch_size: 1
batch_samples_perc: 1.0

# Image
image_name: lena.png
width: 512
height: 512
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-3, 3] 








