# Model Variant (S, L, M)
model: M

# Network
in_features: 3
hidden_layers: 1
hidden_features: [80, 160, 256]
bias: True
max_stages: 3

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [2, 4, 8]
hidden_omega_0: [30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.000000000001
diff_tol: 0.000000001
max_epochs_per_stage: [100, 21, 21]
batch_size: 256 * 256

# Image
image_name: checker.npy
width: 128
height: 128
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
# extrapolate: [-3, 3]








