# Model Variant (S, L, M)
model: L

# Network
in_features: 2
hidden_layers: 3
hidden_features: 64
bias: True
max_stages: 2

# Frequency Initialization
omega_0: 16
hidden_omega_0: 30
superposition_w0: True

# Sampling
sampling_scheme: regular
decimation: False
filter: none # vary between none, laplace and gauss
attributes: ['d1']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: 600
batch_size: 1
batch_samples_perc: 1.0

# Image
image_name: lena.png
width: 128
height: 128
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-3, 3] 