# Model Variant (S, L, M)
model: M

# Network
in_features: 3
out_features: 3
hidden_layers: 1
hidden_features: [[256, 256], [512, 256], [512, 512]]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [4, 12, 24]
hidden_omega_0: [30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1, 'd1': 0}

# Training
opt_method: Adam
lr: 0.001
loss_tol: 0.000000000001
diff_tol: 0.000000001
max_epochs_per_stage: [10, 150, 100, 5]
batch_size: 256 * 256 * 2

# Image
filename: colorful_noise3d128.npy
width: 64
height: 64
depth: 64
channels: 3

test_mesh: bunny.obj
ntestpoints: 290000

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]
slice_views: ['x', 'y', 'z', 'xy']
join_views: False








