# Model Variant (S, L, M)
model: M

# Network
in_features: 2
out_features: 1
hidden_layers: 1
hidden_features: [96, 96, 96, 96, 96, 96, 96]
bias: True
max_stages: 7

# Frequency Initialization
omega_0: [4, 8, 16, 32, 64, 128, 256] 
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: True
period: 0

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']
pmode: 'reflect'

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1}

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.0000000001
diff_tol: 0.00001
max_epochs_per_stage: [2000, 2000, 2000, 2000, 2000, 2000, 2000]
batch_size: 256 * 256

# Image
image_name: camera.png
width: 512
height: 512
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2] 








