
omega_0: [32, 64] 
in_features: 2
hidden_features: [128, 256]
hidden_layers: 1
superposition_w0: False
hidden_omega_0: [60, 80]
sampling_scheme: uniform
multiresolution: pyramid
max_epochs_per_stage: [250, 150]
opt_method: Adam
loss_function: ['d0']
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
batch_pixels_perc: 1.0
batch_size: 1
image_name: lena.png
width: 128
height: 128
channels: 1
stage: 1
max_stages: 2
model: M
useattributes: True
device: cuda
eval_device: cuda
bias: True

save_format: 'general'
extrapolate: [-3, 3] 


