# Model Class (S, L, M)
model: M
positive_freqs: True

# Network
in_features: 1
out_features: 1
hidden_layers: 1
hidden_features: [[4, 32], [64, 24], 8, 16, 32]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [32, 128, 16, 32, 64]
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'hermite'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [4000, 1000, 401, 401, 401, 401, 401]
batch_size: 128 * 128

# Signal
image_name: odd
width: 128
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]