
omega_0: [4, 8, 16, 32, 64, 128] 
in_features: 2
hidden_features: [48, 64, 64, 128, 128, 256]
hidden_layers: 1
superposition_w0: False
hidden_omega_0: [30, 40, 50, 60, 70, 80]
sampling_scheme: uniform
multiresolution: pyramid
max_epochs_per_stage: [500, 450, 350, 250, 150, 100]
opt_method: Adam
loss_function: ['d0']
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
batch_pixels_perc: 1.0
batch_size: 1
image_name: lena.png
width: 128
height: 128
channels: 1
stage: 1
max_stages: 6
model: M
useattributes: True
device: cuda
eval_device: cuda

#save_format: 'general'
#extrapolate: [-3, 3] 


