# Model Class (S, L, M)
model: M
positive_freqs: False

# Network
in_features: 2
out_features: 3
hidden_layers: 1
hidden_features: [[512, 512], [32, 64], [128, 96], 192]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [64, 3, 8, 4, 6, 8, 16, 32]
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.000000000001
diff_tol: 0.000000001
max_epochs_per_stage: [2000, 1000, 600, 400, 400, 400, 400]
batch_size: 256 * 256

# Image
image_name: periodic.png
width: 512
height: 512
channels: 3

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]








