
omega_0: 32
in_features: 2
hidden_features: 256
hidden_layers: 3
superposition_w0: True
hidden_omega_0: 30
sampling_scheme: uniform
multiresolution: capacity
max_epochs_per_stage: 200
opt_method: Adam
loss_function: ['d0']
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
batch_pixels_perc: 1.0
batch_size: 1
image_name: lena.png
width: 128
height: 128
channels: 1
stage: 1
max_stages: 1
model: L
useattributes: True
device: cuda 
eval_device: cuda

#save_format: 'general'