
omega_0: 16
in_features: 2
hidden_features: 64
hidden_layers: 3
superposition_w0: True
hidden_omega_0: 30
sampling_scheme: regular
multiresolution: signal
max_epochs_per_stage: 600
opt_method: Adam
attributes: ['d1']
loss_function: 'mse'
lr: 0.0001
loss_tol: 0.000001
diff_tol: 0.000000000001
batch_samples_perc: 1.0
batch_size: 1
image_name: lena.png
width: 512
height: 512
channels: 1
max_stages: 1
model: L
# Remember to only vary between 'cuda' and 'cpu'
device: cuda 
eval_device: cpu
bias: False

#save_format: 'general'