# Model Variant (S, L, M)
model: M

# Network
in_features: 2
hidden_layers: 1
hidden_features: [128, 256]
bias: True
max_stages: 2

# Frequency Initialization
omega_0: [64, 128] 
hidden_omega_0: [60, 80]
superposition_w0: False

# Sampling
sampling_scheme: regular
multiresolution: pyramid
attributes: ['d1']

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0001
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [250, 150]
batch_size: 1
batch_samples_perc: 1.0

# Image
image_name: lena.png
width: 128
height: 128
channels: 1

# Computation
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
extrapolate: [-3, 3] 