# Model Class (S, L, M)
model: M
positive_freqs: False

# Network
in_features: 2
out_features: 3
hidden_layers: 6
hidden_features: [256]
bias: True
max_stages: 1

period: 0
pmode: "wrap"
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [30, 6, 12, 24, 56, 128]
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: True

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0', 'd1']

# Loss
loss_function: 'hermite'
loss_weights: {'d0': 1, 'd1': 0.0}

# Training
opt_method: Adam
lr: [0.0001, 0.0002, 0.0001, 0.0001, 0.00002, 0.00001]
loss_tol: 0.000000000001
diff_tol: 0.00001
max_epochs_per_stage: [1000, 1200, 1000, 800, 600, 400]
batch_size: 128 * 128 * 2

# Image
image_name: siggraph_asia/dirtymetal.jpg
width: 0
height: 0
channels: 0
color_space: YCbCr

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]
zoom: [2, 4]
zoom_filters: ['linear', 'cubic', 'nearest']