# Model Variant (S, L, M)
model: M

# Network
in_features: 3
out_features: 3
hidden_layers: 1
hidden_features: [[512, 256], [256, 512], [512, 768], [768, 768]]
bias: True
max_stages: 5

period: 2
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [4, 6, 8, 16, 24, 32]
hidden_omega_0: [30, 30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']

# Loss
loss_function: 'mse'
loss_weights: {'d0': 1, 'd1': 0}

# Training
opt_method: Adam
lr: [0.00005, 0.0001, 0.00005, 0.00005, 0.00001]
loss_tol: 0.000000000001
diff_tol: 0.00001
max_epochs_per_stage: [800, 400, 100, 20, 10]
batch_size: 128 * 128

# Image
filename: marble #colorful_noise3d128.npy
width: 512
height: 512
depth: 512
channels: 0
color_space: RGB # L, RGB, YCbCr

test_mesh: bunny.obj
ntestpoints: 290000

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-3, 3]
slice_views: ['x', 'y', 'z', 'xy']
join_views: False
