# Model Class (S, L, M)
model: M
positive_freqs: False

# Network
in_features: 2
out_features: 3
hidden_layers: 1
hidden_features: [[24, 32], [24, 32], [80, 64], [192, 160], [256, 256], [512, 512]]
bias: True
max_stages: 6

period: 2
pmode: "wrap"
domain: [-1, 1]
# mask_color: 130

# Frequency Initialization
omega_0: [3, 4, 8, 16, 32, 64] #[3, 6, 12, 24, 48, 96]
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0', 'd1']

# Loss
loss_function: 'hermite'
loss_weights: {'d0': 1, 'd1': 0.0}

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.000000000001
diff_tol: 0.00001
max_epochs_per_stage: [1400, 1000, 800, 600, 400, 200]
batch_size: 256 * 256 * 2

# Image
image_name: siggraph_asia/redknitwear.jpg #pexels_textures/pic6.png
width: 0
height: 0
channels: 0
color_space: RGB

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cuda

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]
zoom: [2, 4]
zoom_filters: ['linear', 'cubic', 'nearest']