# Model Class (S, L, M)
model: M
positive_freqs: True

# Network
in_features: 1
out_features: 1
hidden_layers: 1
hidden_features: [[16, 32]]
bias: True
max_stages: 1

period: 2
domain: [-1, 1]

# Frequency Initialization
omega_0: [32, 128, 16, 32, 64]
hidden_omega_0: [30, 30, 30, 30, 30, 30, 30]
superposition_w0: False

# Sampling
sampling_scheme: regular
decimation: True
filter: gauss # vary between none, laplace and gauss
attributes: ['d0']
loss_weights: {'d0': 1}

# Loss
loss_function: 'mse'

# Training
opt_method: Adam
lr: 0.0005
loss_tol: 0.00000000000001
diff_tol: 0.00000000001
max_epochs_per_stage: [2000]
batch_size: 256 * 256

# Signal
image_name: freqs
width: 256
channels: 1

# Computation (Only vary between 'cpu' and 'cuda')
device: cuda
eval_device: cpu

# Etc
save_format: 'general'
visualize_grad: True
extrapolate: [-2, 2]